name: Deploy PR Previews

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

permissions:
  contents: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
<<<<<<< HEAD
=======
        if: github.event.action != 'closed'
        env:
            GITHUB_EVENT_NAME: ${{ github.event_name }} # Passes the signal to Vite
>>>>>>> d62d872 (Testing the preview robot)
        run: |
          npm install
          npm run build

      - name: Deploy Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: dist
          umbrella-dir: pr-preview
          action: auto